import os

TRAIN_DATA_PATH = 'Data/fraudTrain.csv'
TEST_DATA_PATH = 'Data/fraudTest.csv'

MODEL_DIR = "models"
MODEL_FILE_NAME = "xgboost_model.pkl"
TRANSFORM_PIPELINE_DIR = "models"
TRANSFORM_PIPELINE_FILE_NAME = "data_transformer.pkl"
FEATURE_NAMES_FILE_NAME = "features_names.json"
FEATURE_NAMES_PATH = os.path.join(TRANSFORM_PIPELINE_DIR, FEATURE_NAMES_FILE_NAME)
TRANSFORM_PIPELINE_PATH = os.path.join(TRANSFORM_PIPELINE_DIR, TRANSFORM_PIPELINE_FILE_NAME)

MODEL_N_ESTIMATORS = 400
MODEL_MAX_DEPTH = 6
MODEL_MIN_CHILD_WEIGHT = 1  
MODEL_GAMMA = 0
MODEL_SUBSAMPLE = 0.8
MODEL_COLSAMPLE_BYTREE = 0.8
MODEL_LEARNING_RATE = 0.1
MODEL_REG_ALPHA = 0.01
MODEL_OBJECTIVE = 'binary:logistic'
MODEL_SCALE_POS_WEIGHT = 1.0
MODEL_EVAL_METRIC = ['aucpr', 'auc']

# MLFlow model registry constants
MODEL_NAME = "FRAUD_XGBOOST"